wallpaper = all,/home/shyam/dotfiles-black-minimal/wallpapers/starry-sky.jpg
wallpaper = eDP-1,/home/shyam/dotfiles-black-minimal/wallpapers/starry-sky.jpg
preload = /home/shyam/dotfiles-black-minimal/wallpapers/starry-sky.jpg
splash = false
