wallpaper = all,file:///home/shyam/dotfiles-black-minimal/wallpapers/starry-sky.jpg
wallpaper = eDP-1,file:///home/shyam/dotfiles-black-minimal/wallpapers/starry-sky.jpg
preload = /home/shyam/dotfiles-black-minimal/wallpapers/starry-sky.jpg
splash = false
